### ISSUE TITLE
ng-multiselect-dropdown/index"' has no exported member 'NgMultiSelectDropDownModule'

### ISSUE THREAD

**Issue by Manpreet-rana** [NileshPatel17/ng-multiselect-dropdown#1]
Hi,
I just import ng-multiselect-dropdown in my application and i am getting this error in app.module.ts:

ng-multiselect-dropdown/index"' has no exported member 'NgMultiSelectDropDownModule' 

Please help.

**Comment by NileshPatel17** [comment]
Please share more details.
