### ISSUE TITLE
node_modules/ng-multiselect-dropdown/index"' has no exported member 'NgMultiSelectDropDownModule'.

### ISSUE THREAD

**Issue by suresh2018** [NileshPatel17/ng-multiselect-dropdown#10]
node_modules/ng-multiselect-dropdown/index"' has no exported member 'NgMultiSelectDropDownModule'.  

i m using this package into angular 5.2..its shows this issue how to fix .please help me

**Comment by NileshPatel17** [comment]
This is an issue with angular-cli..
To fix it, please refer issue compile error #4.

Hope this helps.

**Comment by NileshPatel17** [comment]
here is the link.
_https://github.com/NileshPatel17/ng-multiselect-dropdown/issues/4_

**Comment by Irfan223** [comment]
@NileshPatel17 I want to filter data using lodash with multiselect dropdown list library. Data is coming from server, so how can I filter data based on the selected item object from dropdown list. explain with the working example in stackblitz. It would be highly appreciated.
Thannks in Advance
