### ISSUE TITLE
ng-multiselect-drop down (onDropdownClose) not working

### ISSUE THREAD

**Issue by jeevananthamDviVert** [NileshPatel17/ng-multiselect-dropdown#104]
I tried to use callback method of (onDropdownClose) . but it is not working.

My example.html

  <div class="dropdownclass yearmultiselect">
    <ng-multiselect-dropdown class="form-control" [placeholder]="'Year'" [data]="dropdownYears" (onDropdownClose)="close()"
      [(ngModel)]="selectedYear" [settings]="dropdownSettingsYear">
    </ng-multiselect-dropdown>
  </div>

My example.ts

 close(){
    console.log("called");
  }

**Comment by jeevananthamDviVert** [comment]
In documentation i found this
![dd1](https://user-images.githubusercontent.com/37895069/48757991-8db51480-ecc4-11e8-8f37-4406914927ae.PNG)

But in Your code from Github
![dd](https://user-images.githubusercontent.com/37895069/48758012-a0c7e480-ecc4-11e8-9c9a-cce46f13c9b3.PNG)

Even (onDropDownClose) also not working

**Comment by MAXMASTER001** [comment]
having the same issue...

**Comment by MAXMASTER001** [comment]
solution: onDropdownClose must be onDropDownClose...

**Comment by jeevananthamDviVert** [comment]
@MAXMASTER001 i tried already still it is not working.

**Comment by jeevananthamDviVert** [comment]
@MAXMASTER001 
This is my Html code

" <ng-multiselect-dropdown class="form-control" [placeholder]="'Year'" [data]="dropdownYears" (onDropDownClose)="close()"
      [(ngModel)]="selectedYear" [settings]="dropdownSettingsYear">
    </ng-multiselect-dropdown>"

My .ts code

close(){
console.log("called");
}

My package json

"ng-multiselect-dropdown": "^0.2.3",

Still my ts function not getting called when i tried to close the drop down.

**Comment by jeevananthamDviVert** [comment]
Still no luck :-(

**Comment by MAXMASTER001** [comment]
// .html 
 <ng-multiselect-dropdown
                    [placeholder]="'Dönem seçiniz'"
                    [data]="years"
                    [(ngModel)]="selectedYears"
                    [settings]="dropdownYearsSettings"
                    (onSelect)="onSelectFirma($event)"
                    (onSelectAll)="onSelectAllYears($event)"
                    **(onDropDownClose)="onDropDownClose()"**
                  >
                </ng-multiselect-dropdown>

//.ts

**onDropDownClose** () {
    if (this.selectedYears.length>1) {
    this.grafikGuncelle(); 
     }
    
  }

**Comment by jeevananthamDviVert** [comment]
yeah now i found what was issue .
now its working but i dont know why onDropDownClose getting trigger when open then drop down ?
it should be called only when it is closed right ?

**Comment by vikash09** [comment]
yeah now i found what was issue .
now its working but i dont know why onDropDownClose getting trigger when open then drop down ?
it should be called only when it is closed right ?

is this solved ?

**Comment by josephIDM** [comment]
I am getting this event fired whenever I clicked somewhere in the page. I expect this to be fired only when the dropdown dismisses.

**Comment by Varrion** [comment]
I am having the same issue as well, any fix for this problem ?

**Comment by pbhadauriya** [comment]
Hi Is there any fix for this problem. Angular6  is the version.
<ng-multiselect-dropdown
                                name = "uploadProcesses"
                                [placeholder]="'Select Upload Process'"
                                [data]="uploadProcesses"
                                [(ngModel)]="selectedProcesses"
                                [settings]="dropdownSettings"
                                (onSelect)="onSelectItem($event)"
                                (onSelectAll)="onSelectAll($event)">
                        </ng-multiselect-dropdown>

onSelectItem($event) and onSelectAll($event) are not getting called. and selectedProcesses is also not getting updated. I am not able to save my selections.
