### ISSUE TITLE
No auto unselect on data reload/change

### ISSUE THREAD

**Issue by pckrish** [NileshPatel17/ng-multiselect-dropdown#11]
The selectedItem is not dependent on the data list. any value will be selected irrespective of whether the value is in data source or not. Imagine a scenario of selecting state based on country.
1. Select a country 
2. select a state
3. Select another country , The previously selected state stays even if the present country dont have that state in data source.

**Comment by NileshPatel17** [comment]
I believe, the use case is as follows:
You have got 2 dropdown list-(1) country (2) State
Upon selection/change of country, state dropdown list should get updated.
So ,you need to handle it using on country selection event. On this event, state list should be filtered based on country selected.

Let me know if this is what you are looking for.

**Comment by pckrish** [comment]
@NileshPatel17  The problem is with the previously selected value in state it should deselect. I am still able to see the blue span with close icon. Tried this.selectedItem = [], null, {} etc; with little result. I think when a user fills the selectedItem with objects, we should check if this value is present in the data source. 

To make you better understand I will explain this with an example

Country -> State
1.select India from country dropdown and state data will be populated with indian states.
2. select GOA from it, now we have a blue span with GOA. 
3. Change country to USA. still the GOA selection will be there. 

To get rid of it tried emptying the selectedItem , no result

**Comment by NileshPatel17** [comment]
I got the use-case. When you change country to USA, data should be populated with USA states. So, on select event of country dropdown, you need to populate states. it will not handle automatically.
Pardon me but seems you are not familiar with angular basic.
If you can share code, i can help you.
you can create sample app using codesandbox.com or stackblitz.com.

**Comment by pckrish** [comment]
@NileshPatel17  you don't seem to understand the scenario. I am talking about the selected item shown in blue color ? how to get rid of those ? I am populating states based on country selection(onselect). Cant u try urself with this scenario and undertsand the situation I am talking about ?

**Comment by NileshPatel17** [comment]
Unless and until you share the sample code, i can not help you.
you can create sample app using codesandbox.com or stackblitz.com.

**Comment by pckrish** [comment]
@NileshPatel17 Don't worry have installed another lib that works perfectly

**Comment by NileshPatel17** [comment]
okay. By the way, this component has reached 3k downloads and it get downloaded 50-60/day. No one has face any issue. It works perfectly. it depends on how use use it.

Happy Coding!

**Comment by pavitrag123** [comment]
Hi Nilesh,

Issue is dropdown is not working as expected in cascading scenarios. I've country and state dropdown and able to bind data dynamically to state dropdown based on country. But if state is selected and country dropdown is changed, I'm not to clear the selected state. Can you please check on this

**Comment by Poopandain** [comment]
@pavitrag123
I am facing the same scenario now, did you fix that issue. Please share with me if you have done already. 
Thanks in advance.

**Comment by Poopandain** [comment]
> @NileshPatel17 Don't worry have installed another lib that works perfectly

@pckrish
I am facing the same issue currently, could you please share your fix if you have.

**Comment by NileshPatel17** [comment]
@Poopandain Hey, you are free to use any other library. Why i would be worry, I am not bound by any contract with you.

**Comment by Poopandain** [comment]
@NileshPatel17
How my comments made you an angry, but i need the same scenarios which is previously people asked.

**Comment by NileshPatel17** [comment]
@Poopandain I have gone through the entire thread, and none has shared any sample code so that i can help, and you guys expect me to help. clearly mention your problem statement with actual and expected result with sample code. Otherwise, i can't help you

**Comment by Poopandain** [comment]
@NileshPatel17
I understood your concerns but i found the solution from issue #156
Thanks for your response.
