### ISSUE TITLE
 values show up in input field but dropdowns aren't checked

### ISSUE THREAD

**Issue by azaddeveloper** [NileshPatel17/ng-multiselect-dropdown#111]
I am still facing this issue.

this.selectedItems = [
      { id:10, name: 'Feet' },
      { id:20, name: 'Lower Body' }
    ];

 <ng-multiselect-dropdown  formControlName="body_part"
                    [placeholder]="'Body Part'"
                    [data]="bodyPartArray"
                    required
                    [settings]="dropdownSettings"
                    (onSelect)="onBodyPartSelect($event)"
                    (onDeSelect)="onBodyPartDeSelect($event)"
                    (onDropdownClose)="onDropdownClose()"
                  >
                  </ng-multiselect-dropdown>

**Comment by azaddeveloper** [comment]
Hi,@NileshPatel17   can you look my issue?

**Comment by azaddeveloper** [comment]
@NileshPatel17  My see my code https://stackblitz.com/edit/angular-luazky

**Comment by NileshPatel17** [comment]
this.bodyPartArray and this.selectedItems do not have same type for id property. make it either string or int, it will work.

**Comment by azaddeveloper** [comment]
ok thanks
