### ISSUE TITLE
Unable to import module

### ISSUE THREAD

**Issue by NeilAttewell** [NileshPatel17/ng-multiselect-dropdown#12]
On Angular 4
I ran 
`npm install ng-multiselect-dropdown --save`
In app.module.ts
`import {NgMultiSelectDropDownModule} from 'ng-multiselect-dropdown';`

But I get the following error:

> ERROR in ./node_modules/ng-multiselect-dropdown/index.ts
> Module build failed: Error: /home/####/Workspaces/workspace-sts-3.9.3.RELEASE/####/####/src/angular/node_modules/ng-multiselect-dropdown/index.ts is missingfrom the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
> 
I'd love to use the dropdown you built.

**Comment by NileshPatel17** [comment]
This is an issue with angular-cli..
To fix it, please refer issue compile error #4.

Hope this helps.

**Comment by NileshPatel17** [comment]
i am working on this issue, and will have fixes available in next release.

**Comment by NileshPatel17** [comment]
Fixed. Please take the latest version. No need to do anything additional. Just follow the 2 steps, you did earlier.
