### ISSUE TITLE
No data found message for Search filter functionality missing

### ISSUE THREAD

**Issue by konstantinoskouk90** [NileshPatel17/ng-multiselect-dropdown#122]
When the users **search** for an option and no option is found, no message comes up. I would assume the 'No data available' message would come up in this case. Would you please be able to add it to the control? I feel like it could be beneficial to inform users that no search results were found.

Great work on this control btw! :) It's really good and easy to setup.

**Comment by aarushisampat13** [comment]
I too want this feature to be added in multiselect dropdow.

**Comment by dhsinger75** [comment]
Bumping this possible feature.  My user base is asking for this exact feature.

If there is no development on this, is there a way to detect the filtered items to do something outside of the multi-select box?

I do love this control!
