### ISSUE TITLE
Dropdown settings not accepting placeholder 

### ISSUE THREAD

**Issue by lucianacrx** [NileshPatel17/ng-multiselect-dropdown#137]
No support for sending the _**placeholder**_ as a property in _**dropdown settings**_.

**Comment by prathap0611** [comment]
@lucianacrx 

You can placeholder as an attribute to "ng-multiselect-dropdown". Is that what you are expecting.

**Comment by mao9328** [comment]
@lucianacrx  be careful with the single quotes 

`<ng-multiselect-dropdown
            name="city"
            [placeholder]="'Select City'"
            [data]="cities"
            formControlName="city"
            [disabled]="disabled"
            [settings]="dropdownSettings"
            (onSelect)="onItemSelect($event)">
</ng-multiselect-dropdown>`
