### ISSUE TITLE
Buttons appear over top dropdown list

### ISSUE THREAD

**Issue by striderwhite** [NileshPatel17/ng-multiselect-dropdown#147]
Pretty clear what the issue is here. Any idea how to fix it? (Maybe some cheap css hack?)

![image](https://user-images.githubusercontent.com/6131739/59646815-c96a6c80-9135-11e9-992b-f7fa72d8399b.png)

**Comment by NileshPatel17** [comment]
This issue has nothing to do with the component. hence closing.
