### ISSUE TITLE
Reset not working 

### ISSUE THREAD

**Issue by muthukumarasami** [NileshPatel17/ng-multiselect-dropdown#152]
I am using ng-multiselect-dropdown  in angular 7 project.I need to reset selected values in dropdown .I was trying to reset ngModule value array empty but dom values not cleared and also need validation.Please help me.

**Comment by avi-rav** [comment]
The name of your selected array must be : "selectedItems" And than you can use in your code "this.selectedItems = [];"

**Comment by muthukumarasami** [comment]
I found the issue ,it was **name** not declaring issue in  ng-multiselect-dropdown . I given the solution and now it working fine.
