### ISSUE TITLE
Hi, bro. Its looks cool. Really. Joke. It's not cool. Do you understand that's UNEXPECTED from component, m? 

### ISSUE THREAD

**Issue by kakaby** [NileshPatel17/ng-multiselect-dropdown#154]
https://github.com/NileshPatel17/ng-multiselect-dropdown/blob/6040dfc9488110504f2877edf842628d5238035d/src/ng-multiselect-dropdown/src/multiselect.component.ts#L268

Why if customer love to set in inputs same text as id. It's a bug in each project which uses this component. 

If you want to use such... Exotic functional, plz, let developers some opportunity to configure.

**Comment by NileshPatel17** [comment]
@kakaby why don't you fix, and send PR if you have figure out the issue. I would be happy to merge. Ensure that you run the test post fixing the issue.

**Comment by NileshPatel17** [comment]
it is fixed in new release 0.2.6
