### ISSUE TITLE
Reset not working in dom level- ng-multiselect-dropdown

### ISSUE THREAD

**Issue by muthukumarasami** [NileshPatel17/ng-multiselect-dropdown#156]
I'm using ng-multiselect-dropdown in my angular 7 project.I want to reset dropdown values, so i using below method,but only stored values cleared in variable ; dom values not cleared in my template.And i need validations also.Kindly help me.

`resetSelection() {
  this.selectedTestCompounds = [];        
}

<ng-multiselect-dropdown  
  id="testSample"
  [placeholder]="'select'"
  [data]="sampleList"                                                 
  [(ngModel)]="selectedTestCompounds"                                 
  [settings]="dropdownSettingsTestCompound"                           
  (onSelect)="onItemSelectTestCompound($event)"                       
  (onSelectAll)="onSelectAllTestCompound($event)"
  >
</ng-multiselect-dropdown>
<button (click)="resetSelection()" >clear</button>`

**Comment by avi-rav** [comment]
The name of your selected array must be : "**selectedItems**" (Not "selectedTestCompounds" in your case) And than you can use in your code "this.selectedItems = [];"

**Comment by muthukumarasami** [comment]
I found the issue ,it was **name** not declaring issue in  ng-multiselect-dropdown . I given the solution and now it working fine.
