### ISSUE TITLE
selecting Select All check box selects the disabled item

### ISSUE THREAD

**Issue by sowmyadharg** [NileshPatel17/ng-multiselect-dropdown#163]
If there are disabled checkboxes in the dropdown and when select all is selected, it is selecting the disabled checkboxes as well.

**Comment by NileshPatel17** [comment]
can you please share sample code using codesandbox

**Comment by sowmyadharg** [comment]
Here is the sample code
https://stackblitz.com/edit/angular-ggzkyu

**Comment by NileshPatel17** [comment]
Got it. will be fix in next release.

**Comment by sowmyadharg** [comment]
Hi

When we select a Checkbox the click event $event is not accessible in onSelect Event, Can also you please emit the $event value to onSelect in the next release.

**Comment by NileshPatel17** [comment]
@sowmyadharg event emitter works fine on onSelect. Please share sample code still if you think it doesnt work.

**Comment by NileshPatel17** [comment]
Fixed in 0.2.5. let me know if you find any issue.

**Comment by samarth-baghel** [comment]
I we have one selected field and it's also disabled. but when I clicked on select All then it's deselected first and select other fields and after that I am not able to select this disabled option again. So my question is now how can we stop this I mean disabled value should not be deselected on choose Select All/Deseclect All.
