### ISSUE TITLE
Single select not clearing (though multi-select is clearing)

### ISSUE THREAD

**Issue by ralberts** [NileshPatel17/ng-multiselect-dropdown#17]
We (@randrews86) are trying to clear the component by having a reset button.  It appears to work great for the multiselect though when we configure it for single select it does not clear.  Maybe it's something we are doing wrong?

Here is an example showing a multiselect and singleselect side by side.  If you hit the reset only the multiselect will clear:

https://stackblitz.com/edit/angular-multi-select-bug-pr

**Comment by NileshPatel17** [comment]
It is an bug. It will be fix today.

**Comment by NileshPatel17** [comment]
It has been fix now. Please try with latest version.

**Comment by bbdangar** [comment]
I got the same issue with multi-select. I am using this with FormGroup, not ngModel.

on resetting form group drop-down values remains selected.
