### ISSUE TITLE
enableCheckAll has to be on to see search filter

### ISSUE THREAD

**Issue by randrews86** [NileshPatel17/ng-multiselect-dropdown#18]
This component is very nice!  When initializing setting overrides, you cannot have the search filter turned on and the check all turned off. and see the search filter.  Was this by design?
      
```
{ // these settings will not show the search filter
  allowSearchFilter: true,
  enableCheckAll: false
}
```

**Comment by NileshPatel17** [comment]
It  is an bug. it will be fix today.

**Comment by NileshPatel17** [comment]
It has been fix now. Please try with latest version.
