### ISSUE TITLE
ngModel selected value are object array instead of array of id's

### ISSUE THREAD

**Issue by muralimnmcse** [NileshPatel17/ng-multiselect-dropdown#181]
**Angular version**: 8.0.4

**ng-multiselect-dropdown version**: 0.2.6

**Description of issue**: After upgrading the package from 0.2.5 to 0.2.6 the ngModel selected value becomes array of object instead of array of id's, which is causing issue in my existing project.

**Steps to reproduce**: NA

**Expected result**: [1,2]

**Actual result**: [{id:1,text:'A'},{id:2,text:'B'}]

**Demo**: Please share sample code link using StackBlitz or codesandbox

Any relevant code:
```

```

**Comment by saxcws** [comment]
We should fix the version we're using, this change its breaking my project, and this change should came in another version, in my opinion... They should have upgrade to 1.x...not 0.2.6

**Comment by prateek18aug** [comment]
I am also facing the same issue in my project where array of strings is getting returned as objects

**Comment by NileshPatel17** [comment]
This issue will be fixed today in next release.

**Comment by UserSud** [comment]
Is there a way to choose if the binding can be to an array of int or array of objects?
So my data is an array of objects but I'd like to only store the int of the object keys.
Hope that's somehow possible
Thanks

**Comment by tyronedd** [comment]
> This issue will be fixed today in next release.

Any idea when we can expect this next release?

**Comment by NileshPatel17** [comment]
release new version 0.2.9
Please let me know if find any issue.

**Comment by UserSud** [comment]
Hi, Thanks for the update.
But I can't seem to get the list of int by itself, could you show us an example please?
Thanks

**Comment by NileshPatel17** [comment]
@UserSud I expect from you to share sample code

**Comment by muralimnmcse** [comment]
Hi @NileshPatel17,

Thank you for your valuable effort but still my model is object and not array of int or string.
ng-multiselect-dropdown version: 0.2.10
Sample Code: https://stackblitz.com/edit/angular-tc86ai

**Comment by NileshPatel17** [comment]
@muralimnmcse Please provide more details such as steps to re-produce, actual and expected result.

**Comment by muralimnmcse** [comment]
@NileshPatel17 

Angular version: ^8.0.0

ng-multiselect-dropdown version: ^0.2.10

Description of issue: After upgrading the package from 0.2.5 to 0.2.6 or Higher the ngModel selected value becomes array of object instead of array of id's, which is causing issue in my existing project.

Steps to reproduce: In the Demo sample code in have an object named "mymodel" which i have used has ngModel for ng-multiselect-dropdown. If i select multiple options in drop down the model becomes **"[ { "item_id": 1, "item_text": "Chennai" }, { "item_id": 3, "item_text": "Delhi" }]"** but i expect it to be [1,3]

Expected result: [1,3]

Actual result: [ { "item_id": 1, "item_text": "Chennai" }, { "item_id": 3, "item_text": "Delhi" }]

Demo: https://stackblitz.com/edit/angular-tc86ai

**Comment by NileshPatel17** [comment]
@muralimnmcse I tested it with 0.2.5 version as well. I do not see any difference in terms of behavior. It works as it should work. You need to make adjustment in code as per use-case.
your ```modal``` and ```data``` must be same type. ```modal`` type depends of ```data```.

```
<ng-multiselect-dropdown
  [placeholder]="'custom placeholder'"
  [data]="dropdownList"
  [(ngModel)]="mymodel"
  [settings]="dropdownSettings"  
>
</ng-multiselect-dropdown>
```

**Comment by muralimnmcse** [comment]
@NileshPatel17 Sorry, earlier after 0.2.6 release if the data is array of string the ngmodel was returning array of object now it seems to be fixed in the latest release. The one which i am asking for seems to be a Feature Request which i will raise a separate ticket. Thanks

**Comment by NileshPatel17** [comment]
@muralimnmcse If you pass data source as key-value and expect model to return either key or value, it does not work this way. Library/component can not full fill all use cases, we need to make little code changes to app.

**Comment by muralimnmcse** [comment]
Hi @NileshPatel17 Yes i take your point but when it comes to practical scenario the API team are storing the Id values in the database and they will return the same has array of Id instead of array of items. When we are using two way binding then it will require additional step of mapping those id against the dropdown master data and transforming the same to the item(ngModel). So it will take a overhead during data binding and fetching in dropdown.
Below in the demo i have used Angular Material Multiselect. If we can have the same feature then i will be great.
Demo: https://stackblitz.com/edit/angular-2euuxd

**Comment by ronitkadam777** [comment]
> Hi @NileshPatel17 Yes i take your point but when it comes to practical scenario the API team are storing the Id values in the database and they will return the same has array of Id instead of array of items. When we are using two way binding then it will require additional step of mapping those id against the dropdown master data and transforming the same to the item(ngModel). So it will take a overhead during data binding and fetching in dropdown.
> Below in the demo i have used Angular Material Multiselect. If we can have the similar feature then i will be great.
> Demo: https://stackblitz.com/edit/angular-2euuxd Or https://ng-select.github.io/ng-select#/bindings

I'm facing the same issue. 
One valid use case is pre-populating these dropdowns with user's stored preferences (which are often loaded from a database and only the ids are stored and not the entire object {id: 123, value: DisplayText} . 
The frontend would have to map the retrieved ids with the corresponding optionlist options to create the object the ngModel / formControlName is expecting. 

https://stackblitz.com/run?file=src%2Fbindings-custom-example.component.html, something like a bindValue would be very helpful.
