### ISSUE TITLE
Feature request: Allow filter input to display even it there is no data loaded in the component

### ISSUE THREAD

**Issue by MurrayFurtado** [NileshPatel17/ng-multiselect-dropdown#182]
**Angular version**: 7.2.15

**ng-multiselect-dropdown version**: ^0.2.5

**Description of issue**:
I wish for a user to be able to start typing in the search field to dynamically load results into the dropdown. However for the Search box to be visible at least one row of data is required. Can a flag be added to always show the filter input, regardless of whether data is available.

**Comment by sushil-suthar** [comment]
I am also facing the same issue, Please add this feature as soon as possible.

**Comment by NileshPatel17** [comment]
added new property ```allowRemoteDataSearch``` to allow search remote api when no data is present. this feature is released in 0.2.10

**Comment by sushil-suthar** [comment]
Thanks for the release

**Comment by mmnithin** [comment]
@NileshPatel17 allowRemoteDataSearch worked fine :)

"ng-multiselect-dropdown": "^0.2.10",

 this.dropdownSettings = {
      singleSelection: false,
      idField: 'id',
      textField: 'TestName',
      itemsShowLimit: 1,
      enableCheckAll: false,
      allowSearchFilter: true,
      allowRemoteDataSearch : true
    };
