### ISSUE TITLE
Unable to update dropdown through an observable

### ISSUE THREAD

**Issue by sumitsabhnani** [NileshPatel17/ng-multiselect-dropdown#19]
I am trying to update dropdown data using from a service call inside subscribe but it is not reflecting on the ui... 
my code looks like below
`
data = [{id: 1, text: 'test1'}]

ngOnInit() {
this.service.getResponseData().flatMap(response => response).subscribe(response => {
      this.periods.push({id: response.id, text: response.text});
    });
}
`

When i print it in console it shows all data but in the dropdown it just displays the first one which i added manually...

**Comment by sumitsabhnani** [comment]
here is the url to simulate issue...
https://stackblitz.com/edit/angular-uckc3d

if you see console, you'll see that it is going to error part of the subscribe but items are not getting pushed to dropdown...

**Comment by NileshPatel17** [comment]
You approach is incorrect.
try this code 
`ngOnInit() {
    this.data.push({id: 3, text: 'test3'});
    return this.httpClient.get(this.url).subscribe(response => {
      console.log('data:', this.data);
      this.data.push({id: 1, text: 'test1'});
      this.data.push({id: 2, text: 'test2'});
    }, error => {
      console.log('error');
      // this.data.push({id: 1, text: 'test1'});
      // this.data.push({id: 2, text: 'test2'});
      const oldData=[...this.data];
    this.data=[...oldData,
      {id: 1, text: 'test1'}];
    });
  }`
unless and until you do not re-assign, angular does not know if data has changed, and it does not trigger change detection. thats why it does get added.
