### ISSUE TITLE
Dropdown does not properly close on Firefox

### ISSUE THREAD

**Issue by timosmit** [NileshPatel17/ng-multiselect-dropdown#198]
**Angular version**: 7.2.4

**ng-multiselect-dropdown version**: 0.2.5, but I expect it to be present in latest version as well

**Description of issue**: The dropdown will try to close itself, to immediately reopen itself once it has closed. This is only the case in Firefox; I have not been able to reproduce the issue in Chrome.

**Steps to reproduce**: Open the dropdown, select a value, close the dropdown using the caret/arrow symbol.

**Expected result**: The dropdown should close itself.

**Actual result**: The dropdown reopens itself right after it has closed.

**Demo**: any demo will work

**Comment by geanfrancovolpe** [comment]
Hi @timosmit , have you solved that problem?
