### ISSUE TITLE
Un-selecting the selectedItems items

### ISSUE THREAD

**Issue by Manpreetrajput** [NileshPatel17/ng-multiselect-dropdown#2]
I have fixed a major issue in this plugin:

 initial array [a, b, c, d, e, f, g, h]

Here are steps when issue occur:
1) Pass items in selectedItems array - like you pass [a, b, c]
2) After that select some more options from dropdown  - now you select new items  [d, e]
3)  Then unselect items 'a' or 'b', or 'c' 

Now you see the issue, it will unselect last selected item.

To solve this issue make changes in plugin file /multiselect.component.ts
function - removeSelected

               issue with this line, it remove last selected item from array
                //this.selectedItems.splice(this.selectedItems.indexOf(item), 1);

                //  updated line
                this.selectedItems.splice(this.selectedItems.indexOf(itm), 1);

**Comment by NileshPatel17** [comment]
Hi Manpreet,

It has been fixed now.
You can fork and send PR next time :)

Thanks!
