### ISSUE TITLE
Clear Search text on blur

### ISSUE THREAD

**Issue by gpravnkmr** [NileshPatel17/ng-multiselect-dropdown#21]
The search text is retained even after the user moves away and open the drop down again. Is there a way that we can clear the search text.

**Comment by NileshPatel17** [comment]
how about adding a flag 'clearSearch'. If it is true, search text will be clear upon dropdown close. Bydefault it will be false.

**Comment by NileshPatel17** [comment]
otherwise, it should get clear upon dropdown close automatically.

**Comment by gpravnkmr** [comment]
clearSearch flag would be more generic. So that other users who do not need the text to be cleared can leave it at false.

**Comment by NileshPatel17** [comment]
Added new flag-clearSearchFilter, and updated readme as well. Please wait for the next release.
