### ISSUE TITLE
ERROR TypeError: Cannot read property 'idField' of undefined issue in angular 9

### ISSUE THREAD

**Issue by shivaji33** [NileshPatel17/ng-multiselect-dropdown#216]
**Angular version**:

**ng-multiselect-dropdown version**:

**Description of issue**:

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Demo**: Please share sample code link using StackBlitz or codesandbox

Any relevant code:
```

```

**Comment by wwarby** [comment]
I've also hit this issue. Here is my template HTML:

```<ng-multiselect-dropdown [data]="apps" [settings]="appNameDropdownSettings" formControlName="appName"></ng-multiselect-dropdown>```

And in the component:

```
public get appNameDropdownSettings() {
    return {
      singleSelection: true,
      idField: 'key',
      textField: 'value',
      enableCheckAll: false,
      allowSearchFilter: true
    };
  }
```

**Comment by wwarby** [comment]
I think this might be a duplicate of https://github.com/NileshPatel17/ng-multiselect-dropdown/issues/214

**Comment by AndrewTaftPlusone** [comment]
I had a similar issue i resolved by moving my settings param prior to the data param.  ex. <ng-multiselect-dropdown [settings]="appNameDropdownSettings" [data]="apps" formControlName="appName"></ng-multiselect-dropdown>

**Comment by joaquimcuadro** [comment]
Thank you AndrewTaftPlusone, your solution worked perfectly for me.

**Comment by trandinh135canalcircle** [comment]
AndrewTaftPlusone unblievable , it works , you save my day :))

**Comment by chandanrao611** [comment]
> I had a similar issue i resolved by moving my settings param prior to the data param. ex. <ng-multiselect-dropdown [settings]="appNameDropdownSettings" [data]="apps" formControlName="appName">

Its working fine, you save my time

**Comment by aneudysamparo** [comment]
> I had a similar issue i resolved by moving my settings param prior to the data param. ex. <ng-multiselect-dropdown [settings]="appNameDropdownSettings" [data]="apps" formControlName="appName">

LOL, you save my job!

**Comment by Rakshnaa** [comment]
> I had a similar issue i resolved by moving my settings param prior to the data param. ex. <ng-multiselect-dropdown [settings]="appNameDropdownSettings" [data]="apps" formControlName="appName">

saved my day, Thank you @AndrewLTaft

**Comment by Jubayer07** [comment]
Thank you @AndrewLTaft, your solution worked for me.
