### ISSUE TITLE
Default selected item

### ISSUE THREAD

**Issue by oeknudsen** [NileshPatel17/ng-multiselect-dropdown#22]
Is there any way to set a default selected item?

**Comment by NileshPatel17** [comment]
Yes. Please go though sample code.
https://nileshpatel17.github.io/ng-multiselect-dropdown/

**Comment by briancaldass** [comment]
> Sí. Por favor ve a través del código de muestra. 
> https://nileshpatel17.github.io/ng-multiselect-dropdown/

Its not working :(
