### ISSUE TITLE
onDeSelect() function not available

### ISSUE THREAD

**Issue by jackmasi22** [NileshPatel17/ng-multiselect-dropdown#24]
if i unselect the item from ngModel it is not cleared. So how can i clear(uncheck) the data after i unselect

**Comment by NileshPatel17** [comment]
Can you please share sample code using codesandbox or stackblitz.

**Comment by NileshPatel17** [comment]
onDeSelect() iss available but readme was updated. It will be updated with next release.
By the way, your use-case seems to be different. Please share sample code using codesandbox or stackblitz if you want any help.
Thanks!
