### ISSUE TITLE
Is append to body possible for the dropdown list? 

### ISSUE THREAD

**Issue by nishant14jain** [NileshPatel17/ng-multiselect-dropdown#25]
I have a situation where I need to use multi select dropdown inside a ui-grid table. The table cells are set to overflow hidden so the dropdown get cropped and isn't visible. I cannot set the overflow to visible as that breaks the overall structure of the table. Is it possible to append the dropdown to the body of the document and place it at the right x,y position using position absolute?

**Comment by NileshPatel17** [comment]
I do not have any idea.
