### ISSUE TITLE
Placeholder not working

### ISSUE THREAD

**Issue by Shamonshamonsha** [NileshPatel17/ng-multiselect-dropdown#26]
Custom placeholder is not working 

`{'placeholder:'No subndustry found''}`

**Comment by NileshPatel17** [comment]
Please share sample code via codesandbox.
Ensure that you are using like below. You have to enclose it in single quote.
`<ng-multiselect-dropdown name="city" [placeholder]="'Select City'" >
        </ng-multiselect-dropdown>`
