### ISSUE TITLE
how to use 2 multi-select drop-downs with different sources (Data tag here) and map them with the drop-down settings

### ISSUE THREAD

**Issue by abdulmohammad** [NileshPatel17/ng-multiselect-dropdown#27]
The drop down setting have only idField: 'id', textField: 'itemName', fields. I am using two drop-downs in my angular app, where the drop-downs get data from 2 different models. But the drop down settings here have only id and textfileds which can be mapped for one drop-down. How can I use this plugin with 2 dropdowns in my page with 2 different data sources and id,textfield mapping?

**Comment by NileshPatel17** [comment]
` <ng-multiselect-dropdown name="city" [placeholder]="'Select City'" [data]="countries" formControlName="country" [disabled]="disabled"
          [settings]="dropdownSettings11" (onSelect)="onItemSelect($event)" (onSelectAll)="onSelectAll($event)">
        </ng-multiselect-dropdown>

 <ng-multiselect-dropdown name="city" [placeholder]="'Select City'" [data]="cities" formControlName="city" [disabled]="disabled"
          [settings]="dropdownSettings2" (onSelect)="onItemSelect($event)" (onSelectAll)="onSelectAll($event)">
        </ng-multiselect-dropdown>

 ngOnInit() {
    this.cities = [
      { item_id: 1, item_text: 'New Delhi' },
      { item_id: 2, item_text: 'Mumbai' },
      { item_id: 3, item_text: 'Bangalore' },
      { item_id: 4, item_text: 'Pune' },
      { item_id: 5, item_text: 'Chennai' },
      { item_id: 6, item_text: 'Navsari' }
    ];
    this.selectedItems = [{ item_id: 4, item_text: 'Pune' }, { item_id: 6, item_text: 'Navsari' }];
    this.dropdownSettings2 = {
      singleSelection: false,
      idField: 'item_id',
      textField: 'item_text',
      selectAllText: 'Select All',
      unSelectAllText: 'UnSelect All',
      enableCheckAll: this.showAll,
      itemsShowLimit: 3,
      allowSearchFilter: this.ShowFilter
    };
    this.countries = [
      { id: 1, text: 'india' },
      { id: 2, text: 'usa' },
      { id: 3, text: 'Brazil' },
      { id: 4, text: 'china' }
    ];
    this.selectedCountries = [{ id: 1, text: 'india' }];
    this.dropdownSettings1 = {
      singleSelection: false,
      idField: 'id',
      textField: 'text',
      selectAllText: 'Select All',
      unSelectAllText: 'UnSelect All',
      enableCheckAll: this.showAll,
      itemsShowLimit: 3,
      allowSearchFilter: this.ShowFilter
    };

    this.myForm = this.fb.group({
      city: [this.selectedItems],
countries:[this.selectedCountries]
    });
  }`

hope  this helps.

**Comment by abdulmohammad** [comment]
thanks for the help!
