### ISSUE TITLE
Ng-model not updating correctly

### ISSUE THREAD

**Issue by ralberts** [NileshPatel17/ng-multiselect-dropdown#28]
Hopefully it is just me that did it wrong - though I am not seeing the ng-model being updated correctly.

Here is my example stackblitz:

https://stackblitz.com/edit/angular-multi-select-bug-ng-model?file=app%2Fapp.component.ts

Click the drop-down to select something else and you will notice the output of the ng-model stays the same.

**Comment by ralberts** [comment]
FYI - If you change the version back in the stackblitz to 0.1.5 - it works as expected.

**Comment by ralberts** [comment]
Thanks for any help!

**Comment by NileshPatel17** [comment]
It has been fixed. Please wait for next release, probably today.
Thanks for the patience.
