### ISSUE TITLE
Angular 11 build error

### ISSUE THREAD

**Issue by paulbonner** [NileshPatel17/ng-multiselect-dropdown#282]
**Angular version**: 11

**ng-multiselect-dropdown version**:

**Description of issue**:  ng serve fails due to this error: Error: node_modules/ng-multiselect-dropdown/ng-multiselect-dropdown.module.d.ts:3:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

**Steps to reproduce**: attempt to build a project incorporating this component in Angular 11

**Expected result**:

**Actual result**: build-breaking error:

Error: node_modules/ng-multiselect-dropdown/ng-multiselect-dropdown.module.d.ts:3:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

```

```

**Comment by NileshPatel17** [comment]
@paulbonner This issue has been fixed. Can you please try with new version v0.3.1. let me know if you find any issue.

**Comment by paulbonner** [comment]
Yes, 0.3.1 appears to be working with Angular 11. Thanks

**Comment by bhpanchal** [comment]
@NileshPatel17 ,

Can you please provide sample for Angular 11? I have tried but it was not working.
Here I have attached packages, component and html.

Could you please help me on this?

Thanks,
Bhavin Panchal


[component.txt](https://github.com/NileshPatel17/ng-multiselect-dropdown/files/5953005/component.txt)

![image](https://user-images.githubusercontent.com/53220340/107399769-2135c280-6b27-11eb-9e43-a305b29b2d81.png)

[package.txt](https://github.com/NileshPatel17/ng-multiselect-dropdown/files/5952947/package.txt)

**Comment by NileshPatel17** [comment]
@bhpanchal here is the sample code https://codesandbox.io/s/v031-1vkmo?file=/src/app/app.component.ts

**Comment by NileshPatel17** [comment]
@bhpanchal As of now, both can not be shown together. This can be consider as new feature.

**Comment by bhpanchal** [comment]
> @bhpanchal As of now, both can not be shown together. This can be consider as new feature.

Ok

Thanks,
Bhavin Panchal
