### ISSUE TITLE
ng-multiselect-dropdown in a table, repeated for every row.

### ISSUE THREAD

**Issue by ChathaKiran** [NileshPatel17/ng-multiselect-dropdown#285]
**Angular version**:
Angular CLI: 8.3.3
Node: 14.15.1

**ng-multiselect-dropdown version**: 0.2.10

**Description of issue**: When repeated in a table, how to pre-select each drop down with different set of items.

**Steps to reproduce**:
I've a ng-multiselect-dropdown in each row of an HTML table. Each of the drop downs has the same data source [data]. But each has different pre-selected items. In this case, how would I use - _[(ngModel)]="selectedItems"_ . 

**Expected result**:
I want each of the dropdowns in the table to have different selectedItems pre-selected on initial page load.

**Actual result**:
If I use this - _[(ngModel)]="selectedItems"_ - all the drop downs in the table are getting bound to same set of selected items; meaning, if I select an item in one drop down, it is getting selected in ALL drop downs; Obviously !!!

Please help with this scenario.  Apologize if this is already asked and answered.  If so, please share the link of the issue.

@NileshPatel17

**Comment by NileshPatel17** [comment]
@ChathaKiran you need to have separate variable for each dropdown. create variables say selectedItems1, selectedItems2 etc and bind to respective dropdown
