### ISSUE TITLE
allowSearchFilter not working if limitSelection is enabled

### ISSUE THREAD

**Issue by sumitsabhnani** [NileshPatel17/ng-multiselect-dropdown#29]
Hi,

I'm not sure if this is bug or expected behavior but when I'm setting limitSelecting it automatically disables allowSearchFilter 
Please have a look at below site for sample code
https://stackblitz.com/edit/angular-fjsa3x

Also is there a way to set limitSelection to maximum size by setting it to -1 or something?

**Comment by NileshPatel17** [comment]
Fixed. Please try with v0.1.8
