### ISSUE TITLE
onSelectAll function not working

### ISSUE THREAD

**Issue by Manpreetrajput** [NileshPatel17/ng-multiselect-dropdown#3]
Hi,

I want to do some action on select all event, but onSelectAll is not working .
Here is my code.

in html file

`(onSelectAll)="onSelectAll($event)"`

in ts file
`onSelectAll(items: any) {
        console.log( items);
    }`
not printing anything in console

Thanks.

**Comment by NileshPatel17** [comment]
fixed. Please update the package.
Thanks!
