### ISSUE TITLE
Unable to set the default selected items

### ISSUE THREAD

**Issue by jiahuay** [NileshPatel17/ng-multiselect-dropdown#30]
I followed the example on README to configure my dropdown. I want to have several items selected by default. But setting `[(ngModel)]="selectedItems"` does not work for me. Any ideas?

**Comment by jiahuay** [comment]
@NileshPatel17 

I downgraded this component into AngularJS, since my project is a hybrid AngularJS and Angular 5 app.

Below is my code.

Downgrade the component
```
angular.module(pulseOneAngularJsApp.name).directive('psMultiSelect', downgradeComponent({component: MultiSelectComponent }));

```

Usage in the html
```
      <ps-multi-select
                      [placeholder]="'Please select appliances'"
                      [data]="aac.appliances"
                      ng-model="aac.selectedAppliances"
                      [settings]="aac.dropdownSettings"
                      (on-select)="aac.selectedAppliancesChanged($event)"
                      (on-de-select)="aac.selectedAppliancesChanged($event)"
                      (on-select-all)="aac.selectAllAppliances($event)">
      </ps-multi-select>
```

Controller
```
self.selectedAppliances = [{id: 1, name: 'appliance 1'}];
self.appliances = [{id: 1, name: 'appliance 1'}, {id: 2, name: 'appliance 2'}];
self.dropdownSettings = {
        singleSelection: false,
        idField: 'id',
        textField: 'name',
        selectAllText: 'Select All',
        unSelectAllText: 'DeSelect All',
        itemsShowLimit: 5,
        allowSearchFilter: true
};
```

The multi selection function works fine. The only thing that does not work for me is that the control is unable to pre select some items. Any ideas?

**Comment by jiahuay** [comment]
@NileshPatel17 any input? 

I don't think my case is invalid. There are lots of other people like me using hybrid AngularJS + Angular 5 app.

**Comment by NileshPatel17** [comment]
I do not have expertise on AngularJs. So, can't comment on that.

**Comment by Salwa-BH** [comment]
I had the same problem, here is the solution:
https://www.c-sharpcorner.com/article/multi-select-dropdown-in-angular/
