### ISSUE TITLE
Closing dropdown requires clicking twice (after changing checkbox selection)

### ISSUE THREAD

**Issue by JayBur** [NileshPatel17/ng-multiselect-dropdown#302]
Using Chrome Version 88.0.4324.190 or Version 89.0.4389.82

**Description of issue**:
Closing dropdown requires clicking twice after changing the selection using checkboxes (clicking the cross on a previously selected item already closes the dropdown immediately)

**Steps to reproduce**:
1) Go to sample website: https://nileshpatel17.github.io/ng-multiselect-dropdown/ "Multiple" demo
2) Open/Unfold the dropdown
3) Change the selection using the checkboxes (e.g. using "select all"-checkbox)
4) Click on the dropdown caret 

!) Notice the dropdown refreshes but does not close

5) Click on the dropdown caret again

!) Notice the dropdown now closes

**Expected result**:
To have the dropdown close the first time the caret is clicked on

**Actual result**:
The dropdown only closes after clicking it twice

**Comment by RangerGuan** [comment]
Use ngModelChange，<ng-multiselect-dropdown [data]="dataSource" [(ngModel)]="dropDownSelection" [settings]="dropDownSettings" (click)="dropDownSelect = true" (ngModelChange)="saveFunction($event)"></ng-multiselect-dropdown>

**Comment by JayBur** [comment]
Hi @RangerGuan thanks. I'll assume the workaround is in the 
`[(ngModel)]="dropDownSelection"` and `(click)="dropDownSelect = true" (ngModelChange)="saveFunction($event)"` parts. I'll try it out. 

We're currently using the  `(onSelect)`, `(onDeSelect)`, `(onSelectAll)` and `(onDeSelectAll)` hooks separately and only set the model: `[ngModel]`.

**Comment by Dhaval271993** [comment]
Hii @NileshPatel17 I'm facing this issue in angular 10. (**Closing dropdown requires clicking twice (after changing checkbox selection**)). Can you please help me with this how I can fix it? 
Version : "ng-multiselect-dropdown": "^0.3.4"
In your demo link, The same issue has occurred.
https://nileshpatel17.github.io/ng-multiselect-dropdown/

**Comment by ronnyknight45** [comment]
This is still an issue.

**Comment by jfernandes93** [comment]
Hello @NileshPatel17 i am also facing this similar issue with the dropdown open after closing it and i have noticed that there is an PR open that might resolve this issue. Any updates on it?

Thank you for your time

**Comment by NileshPatel17** [comment]
@jfernandes93 can you please share PR no, i will take a look.

**Comment by jfernandes93** [comment]
https://github.com/NileshPatel17/ng-multiselect-dropdown/pull/322 i believe its this one

**Comment by NileshPatel17** [comment]
@jfernandes93 @ronnyknight45 @Dhaval271993 
Published new version. Please verify with v0.3.8

**Comment by muhammedfasil4042** [comment]
Thanks
