### ISSUE TITLE
Please add tooltip for dropdown elements

### ISSUE THREAD

**Issue by JulyJuli** [NileshPatel17/ng-multiselect-dropdown#317]
Sometimes it is necessary to have tooltips especially when max-width has to be defined and dropdown elements values are wider.
If you ok with this enhancement I will create a PR

**Comment by dsuwirya-cloudwiz** [comment]
+1

When selection is being truncated due to max width, would like to have the tooltip appear displaying complete value text on hover please:

![image](https://user-images.githubusercontent.com/81872477/126920157-c7317364-3dfd-4d77-abdc-ea26fde87fc0.png)

**Comment by dsuwirya-cloudwiz** [comment]
@NileshPatel17, does this feature make it to v1.0.0? "tooltipField" seems missing from v1.0.0.

**Comment by YuliiaKovalova** [comment]
thank you ;)
