### ISSUE TITLE
Cannot preselect items when singleSelection is false with latest version 

### ISSUE THREAD

**Issue by junaidsarwarpk** [NileshPatel17/ng-multiselect-dropdown#33]
When I set singleSelection to true it preselects the values successfully but when I change singleSelection to false it does not work anymore.
**It was working perfectly fine with older version**.
here is a small code snippet that might help:

this.filters_settings = {
		  "singleSelection": false,
		  "selectAllText": "Select All",
		  "unSelectAllText": "UnSelect All",
		  "allowSearchFilter": true,
		  "itemsShowLimit": 2,
		  "closeDropDownOnSelection": false,
		  "idField": "name",
		  "textField": "label"
	  }
<ng-multiselect-dropdown
				       name="filters"
				       [data]="filtersList"
				       [settings]="filters_settings"
				       [(ngModel)]="filters.standards"
				       (ngModelChange) = onFiltersSelect(filters.standards)
				       >
</ng-multiselect-dropdown>

**Comment by NileshPatel17** [comment]
Please share sample code using https://codesandbox.com or https://stackblitz.com

**Comment by mrugank84** [comment]
I agree to junaidsarwarpk. in multiseelct mode selected item does not work.

**Comment by mathisGarberg** [comment]
I'm experiencing the same problem with same code as above.

**Comment by junaidsarwarpk** [comment]
sample code submitted by @mrugank84 above

**Comment by tschmidt01** [comment]
Same for me.

**Comment by Ahmad-Magdy** [comment]
@NileshPatel17  another example
https://angular-ggwyj9.stackblitz.io
i preselected A and i provide values A,B and C, and it didn't select the predefined value

**Comment by junaidsarwarpk** [comment]
@NileshPatel17 any update on this issue?

**Comment by KunalPhoneGap** [comment]
@NileshPatel17 is this plugin created by you ? or just a customization of available multi select dropdown ?

**Comment by NileshPatel17** [comment]
Its fixed now. Please wait for the next release.
@KunalPhoneGap I needed such control in one of my project, found one but i had to customized as per my use-case, and later on publish on github so that others can use it, and kept improving.
