### ISSUE TITLE
Emit the source object in addition to label and id

### ISSUE THREAD

**Issue by tschmidt01** [NileshPatel17/ng-multiselect-dropdown#35]
For complex objects, it would be handy to also receive the complex object instead of just `{id: string, label: string}`.

**Comment by danilorb** [comment]
Any solution? I'm also having the same problem.
I need the whole object.

**Comment by tschmidt01** [comment]
@danilorb Sadly not. It seems that this library doesn't get maintained well enough for us to continue using it, so we're going to build our own component for it.

**Comment by danilorb** [comment]
Thanks @tschmidt01 , I will be following the development process. If you need help, you can call me. Hugs.

**Comment by NileshPatel17** [comment]
@danilorb PR is also welcome. but anyway, Good Luck
