### ISSUE TITLE
Open dropdown by default

### ISSUE THREAD

**Issue by amahmoud76** [NileshPatel17/ng-multiselect-dropdown#36]
Is there a way to make the dropdown open by default when you load the page instead of clicking on the caret? I know it might sound ridiculous, but the control I am trying to implement is exactly what the ng-multiselect-dropdown offers minus the dropdown?

**Comment by NileshPatel17** [comment]
It can be done. However such use-cases would be very rare. Are you building some kind of multi-select listbox?

**Comment by amahmoud76** [comment]
Yes, listbox with exact same behavior of the dropdown. Is there a property to enable that?

**Comment by NileshPatel17** [comment]
I want to keep it as dropdown rater than listbox. So, I would advise you to find such listbox component or maintain own copy of this component.
