### ISSUE TITLE
Web page height problem when dropdown is open

### ISSUE THREAD

**Issue by saradev1927** [NileshPatel17/ng-multiselect-dropdown#365]
**Angular version**: 11.0.7

**ng-multiselect-dropdown version**: 0.3.8

**Description of issue**: My multiselect contains many elements, 200 or more, when I open it, the scrollbar of the web page decreases and the height of the page increases in relation to the items contained in the dropdown.

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Demo**: Please share sample code link using StackBlitz or codesandbox

Any relevant code:
```

```

**Comment by JazzCF** [comment]
same issue here
