### ISSUE TITLE
Pre-select items

### ISSUE THREAD

**Issue by Dirtyburger1338** [NileshPatel17/ng-multiselect-dropdown#37]
Is it possible to have a chose some options to be checked when the select is initialized?

**Comment by mferraricloudsurfers** [comment]
Found an error in sources. In writeValue method, change the following code
`if (this._settings.limitSelection)` with `if (this._settings.limitSelection && this._settings.limitSelection > 0)`. With this fix, now works.

**Comment by tschmidt01** [comment]
This is already addressed here: https://github.com/NileshPatel17/ng-multiselect-dropdown/issues/33#issuecomment-390381930

**Comment by bbdangar** [comment]
I am also facing this issue. unable to set pre-select options in the multi-select drop-down.

**Comment by tschmidt01** [comment]
@NileshPatel17 any ETA on the release?

**Comment by NileshPatel17** [comment]
@tschmidt01 Checkout the new release.
