### ISSUE TITLE
Preselected values now show up in input field but dropdowns aren't checked

### ISSUE THREAD

**Issue by tschmidt01** [NileshPatel17/ng-multiselect-dropdown#38]
**Version: 0.19**

![screen shot 2018-05-23 at 09 45 30](https://user-images.githubusercontent.com/15064827/40410436-1d325e50-5e6e-11e8-8ac2-66cbd60981cd.png)

**Comment by NileshPatel17** [comment]
Please share sample code using codesandbox or https://stackblitz.com

**Comment by MiRush94** [comment]
I noticed that the preselected values only show up in my input field, once I click somewhere on the page, not before.  (well... Sometimes they show up without me having to click but mostly they don't.)
Selection shows up in the dropdown below if I open it so thats fine. is this a bug or a rendering issue ? 

sample code:  
ng-multiselect-dropdown [placeholder]="'Select filters...'" [data]="filters" formControlName="reportingFilters" [settings]="filterDropdownSettings">
            </ng-multiselect-dropdown>

now I am using reactive forms, and it works but this additional click on page load is kinda annyoing :D any suggestions? I don't need [(ngModel)]="reportingFilters" as formControlName does just fine for me.

**Comment by NileshPatel17** [comment]
@MiRush94  one line code can not help me to reproduce the issue. please share sample code using stacklitz.com or codesandbox. its pretty easy to use and wont take much time.

**Comment by MiRush94** [comment]
Hi @NileshPatel17 , found the issue, I did need to use [(ngModel)] with the same as formControlName

**Comment by NileshPatel17** [comment]
not necessary, you can check demo page and look for multiple selection. i have used reactive forms.
https://nileshpatel17.github.io/ng-multiselect-dropdown/
Otherwise, if you can share sample code with sandbox.com, i can help you

**Comment by MiRush94** [comment]
It's fine now, but thank's for the help and the demo :)

**Comment by maheshshinde9** [comment]
Using reactive forms in Angular 6 with http get API it works but as MiRUsh94 mentioned above we need to click  any where on page after page load to show selected value.
See below stackblitz (I have used settimeout instead of http get just for example):
https://stackblitz.com/edit/angular-5ktaht

**Comment by NileshPatel17** [comment]
@maheshshinde9 @MiRush94 You were not used reactive form correctly. 
You must initialize the value
```this.myForm = this.fb.group({
      city: [this.selectedItems]
    });
```
here is the rectified code.
```
ngOnInit() {
    this.dropdownSettings = {
      singleSelection: false,
      idField: 'item_id',
      textField: 'item_text',
      selectAllText: 'Select All',
      unSelectAllText: 'UnSelect All',
      itemsShowLimit: 3,
      allowSearchFilter: this.ShowFilter
    };
    this.cities = [
      { item_id: 1, item_text: 'New Delhi' },
      { item_id: 2, item_text: 'Mumbai' },
      { item_id: 3, item_text: 'Bangalore' },
      { item_id: 4, item_text: 'Pune' },
      { item_id: 5, item_text: 'Chennai' },
      { item_id: 6, item_text: 'Navsari' }
    ];
    this.selectedItems = [{ item_id: 4, item_text: 'Pune' }, { item_id: 6, item_text: 'Navsari' }];
    this.myForm = this.fb.group({
      city: [this.selectedItems]
    });

     }
```

**Comment by maheshshinde9** [comment]
Even though I made following change in ngOnInIt, still it's not working:
 this.myForm = this.fb.group({
                city: [this.selectedItems]
            });

Note - Just for example purpose I am using setTimeout instead of actual http get call (It works without setTimeout). See below URL:
https://stackblitz.com/edit/angular-5ktaht

**Comment by NileshPatel17** [comment]
Please check my code properly. sequence of statement is very important.

https://stackblitz.com/edit/angular-hravnz

**Comment by MiRush94** [comment]
@maheshshinde9 , with ngModel it works, but as we made a production build, we had to remove [(ngModel)] (we are also using angular 6.) However, it seems to work just fine with the production build.

**Comment by maheshshinde9** [comment]
@MiRush94,  Do you have any working example (without [ngModel] and with settimeout or actual http call) or stackblitz url?

**Comment by Sharondio** [comment]
I'm having this same issue. I have to wait for http calls to populate both the values and the selected values. If I click into the field, the values are selected, and the tags are re-drawn.  But there doesn't seem to be a way to trigger the re-draw to happen on a reactive forms update.

See example here: https://stackblitz.com/edit/angular-x4tqcx

**Comment by NileshPatel17** [comment]
@maheshshinde9 

please checkout this
https://stackblitz.com/edit/issue-38

**Comment by Sharondio** [comment]
Basically you have to set both the values and the selected values at the same time. This works, but still hoping you find the real answer.

**Comment by NileshPatel17** [comment]
@Sharondio  You can use ngModel but recommended way to update it to use patchValue/setValue as per the Angular official documentation. It has been deprecated in v6 and will be removed in v7.
```
 <ng-multiselect-dropdown
            name="city"
            [placeholder]="'Select City'"
            [data]="cities"
			[(ngModel)]="selectedItems"
            formControlName="city"
            [disabled]="disabled"
            [settings]="dropdownSettings"
            (onSelect)="onItemSelect($event)">
        </ng-multiselect-dropdown>
```
You can read more here
https://angular.io/api/forms/FormControlName#example

**Comment by Sharondio** [comment]
@darmie I was able to get it working by setting the select values at the same time that I set the selected value. Because when I was populating the form value selected before the items returned from the query, it wasn't working. So resolve all of your queries, then populate everything.

**Comment by azaddeveloper** [comment]
@NileshPatel17 @MiRush94   I am facing same issue.

**Comment by MM40** [comment]
Hi, please make sure the type is correct while re-assigning values. My problem was "1" instead of 1 for item_id.
I converted using parseInt and now works fine. Also, try to set a flag using ngIf after re-assigning values.

**Comment by huzaifa074** [comment]
I just got into this situation using formControlName where pre-selected items were not displaying unless I click somewhere. I tried patchValue and setValue both didn't work. Then the workaround which worked for me was to **add ngModel along with formControlName** and I not even assigned any value to ngModal array it worked by just defining the array empty. I assigned the value to formControl as I was doing earlier just added ngModal.

**Comment by MalleshSalla** [comment]
> not necessary, you can check demo page and look for multiple selection. i have used reactive forms. https://nileshpatel17.github.io/ng-multiselect-dropdown/ Otherwise, if you can share sample code with sandbox.com, i can help you

**Comment by saurabhgit1** [comment]
I was also facing the same issue.
As per my findings, if we update the data attribute again during the http call or setTimeout, it works.

@NileshPatel17  I have made few changes in your stackblitz to reproduce this issue.
https://stackblitz.com/edit/issue-38-ird4pu
You were initializing cities inside setTimeout which might not be the case always.
I am using this.cities = [...this.cities] inside setTimeout in order to fix the issue.
