### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by yvanvds** [NileshPatel17/ng-multiselect-dropdown#4]
Hey

Your component seems very cool, but i got this error when I'm using it:

`Failed to compile.

./node_modules/ng-multiselect-dropdown/index.ts
Module build failed: Error: E:\OurtripSite\site\node_modules\ng-multiselect-dropdown\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (E:\OurtripSite\site\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:677:23)
    at plugin.done.then (E:\OurtripSite\site\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app.module.ts 27:32-66
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts`

Any chance you know what this is about? Looks like angular is blaming you :-)

**Comment by NileshPatel17** [comment]
I gave it a try in codesandbox, and it worked fine.
here is the link: 
https://codesandbox.io/s/730k5vy381
I dont see any reason why it did not work at your end. Can you please share the steps you followed.

**Comment by nasr18** [comment]
I tried more than 2 `MultiSelect Dropdown`. Only this `UI` fitting with my template. So Implemented this module in my project and got build errror. After doing google, I found the fix and fixed this issue. Running perfecty in my project and looks good. 

Only think I feel missing is, `onRemove` event. It  would be more helpful if u add this event.

**Comment by NileshPatel17** [comment]
Its there-_(onDeSelect)="onItemDeSelect($event)"_

**Comment by yvanvds** [comment]
Hi.

Just tested again with a new project. These are the only steps I needed to recreate it:

`ng new testapp`
`cd testapp`
`npm install ng-multiselect-dropdown`

Next, I edit app.module.ts and add:
`import {Ng2MultiSelectDropDownModule} from 'ng-multiselect-dropdown';`
and at import: `Ng2MultiSelectDropDownModule.forRoot()`

Then:
`ng serve`

This will return the error in my original message. Undoing changes in app.module.ts is enough to get the site running again.

**Comment by NileshPatel17** [comment]
By following steps you mentoined, i could able to reproduce the issue.
However it seems to be issue with angular 5.0 and angular-cli 1.5.0. checkout below link
_https://github.com/angular/angular-cli/issues/8284_

**Comment by nasr18** [comment]
@yvanvds just add these lines in `tsconfig.json`

```
"include": [
    "src/**/*",
    "node_modules/ng-multiselect-dropdown/index.ts"
  ]
```

it will work for sure.

**Comment by NileshPatel17** [comment]
Yes.. i know that but i need to add it for each package i add.  that's weird. It should pick it up automatically. I am sure angular-cli team will fix this or could have fix it and might be available in next release.

**Comment by yvanvds** [comment]
Ok, thanks for the help. I'll keep an eye on the angular updates.

**Comment by Elegant-Bird** [comment]
@yvanvds I found a workaround for this issue 
Copy the ng-multiselect-dropdown from the node_modules (the entire folder)
Drop it in your app somewhere and include it in the app module using your local directory instead of node_modules
That fixed it for me

`import { Ng2MultiSelectDropDownModule} from "../shared/directives/ng-multiselect-dropdown";

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ProviderRoutingModule,
    ReactiveFormsModule,
    SharedModule,
    HttpModule,
    OrderModule,
    TextMaskModule,
    Ng2MultiSelectDropDownModule.forRoot()
  ],`

**Comment by FOSSKolkata** [comment]
I was also getting the same error, added "include" section in tsconfig.app.json, which is within src folder of the projects created using angular cli : 
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": []
  },
  "include": [
    "**/*",
    "../node_modules/ng-multiselect-dropdown/*.ts"
  ],
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}

**Comment by NileshPatel17** [comment]
@FOSSKolkata No need to do this anymore. This issue had been taken care. Please take the latest code.
Thanks!

**Comment by jackmasi22** [comment]
(onDeSelct) event is not firing. And the documentation also not mentioned about this event.

**Comment by imraqes** [comment]
Hey, I am not able to fire `(onFilterChange)="onFilterChange($event)"` onFilterChange event, can you help me ?

**Comment by avinexus7** [comment]
Hi,
Using node 8.11.3 and npm 6.2.0; @angular/cli 6.0.8; getting the same error:

> Module not found: Error: Can't resolve 'angular2-multiselect-dropdown/angular2-multiselect-dropdown' in 'C:\spaat\inventory_management\src\app'
