### ISSUE TITLE
enableCheckAll is not getting set to false, in case of multiple select with search functionality

### ISSUE THREAD

**Issue by CoderAkash** [NileshPatel17/ng-multiselect-dropdown#41]
enableCheckAll is not getting set to false, in case of multiple select with search functionality.

**Comment by bbdangar** [comment]
yes, I am also facing this issue.

**Comment by NileshPatel17** [comment]
Fixed. Please wait for the next release

**Comment by NileshPatel17** [comment]
Its fixed.

**Comment by BuntyBru** [comment]
I am not able to use 
itemsShowLimit  
Its not working

<angular4-multiselect [data]="backService.answerDropdown" [(ngModel)]="selectedPincodeItems" [settings]="dropdownSettings" 
                       (onSelect)="onItemSelect($event)" 
                       (onDeSelect)="OnItemDeSelect($event)"
                       (onSelectAll)="onSelectAll($event)"
                       (onDeSelectAll)="onDeSelectAll($event)"></angular4-multiselect>


this.dropdownSettings = { 
  itemsShowLimit:2,
          singleSelection: false, 
          text:"Select Branches",
          selectAllText:'Select All',
          unSelectAllText:'UnSelect All',
          enableSearchFilter: true,
          classes:"myclass custom-class",
          maxHeight:150,
          disabled:false
        };   

All the elements come in the box instead of 2

**Comment by sharmilaVJ** [comment]
I want to hide select ALL option  from list... so i tried    "enableCheckAll "  false  but it is not working....
this.dropdownSettings = {
    singleSelection: false,
    idField: 'id',
    textField: 'text', 
    selectAllText: 'Select All',
    unSelectAllText: 'UnSelect All',
    enableCheckAll : false
    itemsShowLimit: 3,
    allowSearchFilter: false
};

am getting below error
enable checkAll does not exist in the type......

Kindly help me if am wrong
