### ISSUE TITLE
onFilterChange is not working

### ISSUE THREAD

**Issue by imraqes** [NileshPatel17/ng-multiselect-dropdown#45]
Hi Nilesh, I have checked your code and you seem to missing `(ngModelChange)="onFilterTextChange($event)"` on multiple place, resulted `onFilterChange` is not working, I have made the fix for me.

At one place your code says

`<input type="text" [readOnly]="disabled" [placeholder]="_settings.searchPlaceholderText" [(ngModel)]="filter.text"  (ngModelChange)="onFilterTextChange($event)">`

and another place it says

`<input type="text" [readOnly]="disabled" [placeholder]="_settings.searchPlaceholderText" [(ngModel)]="filter.text">
`
You have missed using ngModelChange on some conditions on search input. Please make the fix for others.

**Comment by NileshPatel17** [comment]
Sorry, I was busy with other stuff. So, i could not get time to reply.
Coming back to this issue. seems we have duplicate template.
 ```<div class="dropdown-list" [hidden]="!isDropdownOpen"></div>```
I would be fixing it, and publish new version.
Thanks for using this component, and feel free to send PR in fixture.
Happy Coding!

**Comment by ChengYuHin99** [comment]
Hey, could you please fix this issue for others?
I am leaving this control because of this issue.

**Comment by NileshPatel17** [comment]
Fixed now.
