### ISSUE TITLE
How to load dynamic data in dropdown?

### ISSUE THREAD

**Issue by komalkedia** [NileshPatel17/ng-multiselect-dropdown#5]
I need to load dynamic data. But its not working. Can we add that?

**Comment by NileshPatel17** [comment]
This component does not support such feature-dynamic data loading. May be in future i can add that.
by the way, what is your use-case?? Do you want to add more data upon user interaction such as on button click.

**Comment by komalkedia** [comment]
Yes, on change of an option, I want to load different data in drodown.

*Thanks & Regards:*
*Komal Kedia*

**Comment by NileshPatel17** [comment]
Hope this helps
_https://codesandbox.io/s/821vnk8lzj_
upon selection of country, respective cities gets populated in dropdown.

**Comment by chetanbirajdar** [comment]
How can I get the dropdown list from database.  

HTML Code
 
<ng-multiselect-dropdown [placeholder]="'Select'" [data]="VendorList" [(ngModel)]="selectedVendors" [settings]="VendorSettings"
          (onSelect)="onVendorSelect($event)" (onSelectAll)="onSelectAllVendor($event)">
        </ng-multiselect-dropdown>

Component.ts code
   this.settingsService.GetVendorList().subscribe(res => {
      this.VendorList = res;
    });

this JSON Data I am getting in this.vendorlist is {
id: 1, name : Chetan,
id: 2, name : Akash
}

how do I bind name , id to the [data]

any help is appeciated.

**Comment by sharmilaVJ** [comment]
Not able to dynamically  add data to dropdownlist  from DB....kindly need help

<ng-multiselect-dropdown 
name="roles"
[data]="rolesList"
[settings]="dropdownSettings" >

</ng-multiselect-dropdown>

ts.
 rolesList = [ ];
  for (let role of this.UserOnlaod.UserRole) {
            this.rolesList.push(role.code);
            
        }

**Comment by Md-Aman** [comment]
Any update to dynamically add data to a dropdown list.

**Comment by ProximaHaiz** [comment]
@Md-Aman Try this: https://www.npmjs.com/package/angular2-multiselect-dropdown

**Comment by igorkofman** [comment]
> Hope this helps
> _https://codesandbox.io/s/821vnk8lzj_
> upon selection of country, respective cities gets populated in dropdown.

@NileshPatel17 - there is no country selector in this code sandbox so I have no idea what you're talking about.  You should make it clear that this module doesn't support dynamic data binding.

**Comment by mrturing45** [comment]
You can absolutely load dynamic data. push the data you get form service into any array or your interface array. Change idField and textField as your need.

**Comment by UserSud** [comment]
I'm trying to push a new item into the mutli select dropdown and have added to the sample code as below:
https://codesandbox.io/s/angular-y3uo4

I've added a button a push a new item into the cities array and from the console.log I can see that the array is updated but the dropdown list does not reflect this change.  

Is there a function we can call to refresh the dropdown items?

**Comment by NileshPatel17** [comment]
Below code wont work. you need to understand how angular change detection works.
```
 this.cities.push({ item_id: 7, item_text: 'Test Item' });
```
There are many way. below is one of them. try this
```
this.cities=this.cities.concat({item_id:7,item_text:'test'})
```

**Comment by UserSud** [comment]
Hi Nilesh,
Many thanks for your swift response! Your advice totally solved my problem.
I was reading the values from a database call and pushing the items into the bound array.  
Now that I'm using concat every is now working great. Thanks again!

**Comment by SmitSabuwala** [comment]
@NileshPatel17 Thanks for sharing the code of contact. It's solved my problem

**Comment by nehal076** [comment]
Using `concat` is like using a hack. And why `push` doesn't work?

**Comment by NileshPatel17** [comment]
@nehal076 `push` won't work. do you know about immutability? Please read about it more.
`push` does not create new reference. Hence angular change detection can not detect it. so, it do not work.

**Comment by Nishant-Gosavi** [comment]
@NileshPatel17, I want to add dynamic data in ng-multiselect-dropdown with the help of external class method(Module), can I do it, is there any way?

Thank you.

**Comment by Nishant-Gosavi** [comment]
> @NileshPatel17, I want to add dynamic data in ng-multiselect-dropdown with the help of external class method, can I do it, is there any way?
> 
> Thank you.

Also If anyone having solution for the same, please reply

**Comment by nehal076** [comment]
> Below code wont work. you need to understand how angular change detection works.
> 
> ```
>  this.cities.push({ item_id: 7, item_text: 'Test Item' });
> ```
> 
> There are many way. below is one of them. try this
> 
> ```
> this.cities=this.cities.concat({item_id:7,item_text:'test'})
> ```



> > @NileshPatel17, I want to add dynamic data in ng-multiselect-dropdown with the help of external class method, can I do it, is there any way?
> > Thank you.
> 
> Also If anyone having solution for the same, please reply



> Below code wont work. you need to understand how angular change detection works.
> 
> ```
>  this.cities.push({ item_id: 7, item_text: 'Test Item' });
> ```
> 
> There are many way. below is one of them. try this
> 
> ```
> this.cities=this.cities.concat({item_id:7,item_text:'test'})
> ```

@Nishant-Gosavi

**Comment by Nishant-Gosavi** [comment]
Thanks @nehal076 for quickly getting back to me however the first code actually worked for me. Here is the snippet
`this.dropdownList.push({item_id: this.xyz.value, item_text: this.xyz.text})`

**Comment by Nishant-Gosavi** [comment]
@NileshPatel17 @nehal076 I want to add validations to the ng-multiselect-dropdown component, how can I do this, is there any way to do this? If anyone knows the solution please reply. Thank you

**Comment by marceloscientist** [comment]
Guys, I can't find a way to find out when the data is all unselected. Then, I've tried guessing (onDeSelectAll), and that worked nicely. However, the Sonar complained! Because of that, I need to understand how can I understand if there's no data selected because I needed to update the data correctly afterward!

**Comment by marceloscientist** [comment]
Forget mates, ,,,,,,,the selectedItems already keep all the info, then... There's no need anymore to handle by myself. Cheers!!!

**Comment by Sreesanth46** [comment]
```
  dropdownList : any
  
dropdownSettings : IDropdownSettings = {
    idField: 'employeeId',
    textField: 'employeeName',
    allowSearchFilter: true,
    itemsShowLimit: 2,
  }

  ngOnInit(): void {
    this.getEmployee()
}

  getEmployee() {
    this.managerApiService.getEmployee().subscribe({
      next : (res) => {
        this.dropdownList = res
      },
      error : (err) => console.log("Error getting employee" + err)
      
    })    
  }

```

Try this

**Comment by raviagheda** [comment]
I've managed to update the list from API based on a search query, but how can I show the loader while the API call is in progress?
