### ISSUE TITLE
How we can remove "Check All"

### ISSUE THREAD

**Issue by rahulpathak** [NileshPatel17/ng-multiselect-dropdown#58]
Hi @NileshPatel17,
How we can remove "Check All" in dropdown. i tried with showCheckAll: false  but it's not working.

```
this.dropdownSettings = {
singleSelection: false,
showCheckAll: false,
showUncheckAll: false,
idField: 'item_id',
textField: 'item_text',
itemsShowLimit: 1,
allowSearchFilter: false
};
```

**Comment by NileshPatel17** [comment]
with below property, you can show/hide "Select All" option:
 "enableCheckAll": false/true
