### ISSUE TITLE
Unable to change the drop down list

### ISSUE THREAD

**Issue by chiragdhawan1995** [NileshPatel17/ng-multiselect-dropdown#61]
I'm trying to update the drop down list on a particular event. I'm able to update the array which populates the drop down list but the same is not getting reflected on front end.

`<ng-multiselect-dropdown
  [placeholder]="'Select Cities 2'"
  [data]="dropdownList2"
  [(ngModel)]="selectedItems2"
  [settings]="dropdownSettings2"
  (onSelect)="onItemSelect2($event)"
  (onSelectAll)="onSelectAll2($event)"
>
</ng-multiselect-dropdown>`

When I update the array dropdownList2, the list on front end isn't updated and shows the old values.

**Comment by NileshPatel17** [comment]
please share sample code using codesandbox or https://stackblitz.com, otherwise very difficult to help you

**Comment by madhuri03** [comment]
Hi @NileshPatel17  Here is sample code https://stackblitz.com/edit/angular-kqrdtp , In this example noramal select box get updated by new city added from input. but multiselect doesn't.

**Comment by NileshPatel17** [comment]
@madhuri03 Not sure if you know how change detection works in angular. anyway, here is the fix.

```
 addNewLocation(cityName) {
    if(cityName !== '') {
      const listLength = this.dropdownList.length;
      // this.dropdownList.push({item_id: listLength, item_text: cityName});
      this.dropdownList=this.dropdownList.concat({item_id: listLength, item_text: cityName});
      console.log(this.dropdownList);
    }
  }
```

**Comment by madhuri03** [comment]
Thanks for the reply. It is working now :)

Regards,
Madhuri Bhamre
