### ISSUE TITLE
Option with value = 0 doesn't display

### ISSUE THREAD

**Issue by akhodachenko** [NileshPatel17/ng-multiselect-dropdown#67]
Looks like when you have a data option with value 0 the select doesn't pick it up.

**Comment by NileshPatel17** [comment]
please share sample code using codesandbox or https://stackblitz.com, otherwise very difficult to help you

**Comment by NileshPatel17** [comment]
this issue has been fixed, and will be available in next release.

**Comment by NileshPatel17** [comment]
Its fixed in version 0.2.1
