### ISSUE TITLE
How to update the model if I unchecked the option 

### ISSUE THREAD

**Issue by saurabh147sharma** [NileshPatel17/ng-multiselect-dropdown#7]
First I checked the option and get the value by onItemSelect() but how to get the event of how to update my model if I unchecked the option.

**Comment by NileshPatel17** [comment]
this components exposes 4 event handlers:-
1) onSelect: fires when an item is checked
2) onDeSelect: fires when an item is unchecked
3) onSelectAll: fires when all items are checked
4) onDeSelectAll: fires when all items are unchecked

Hope it will help.

**Comment by saurabh147sharma** [comment]
Hello Nilesh,
Thank you very much. These functions works for me and solved my issue.

**Comment by NileshPatel17** [comment]
Welcome.
Happy Coding!
