### ISSUE TITLE
Placeholder for "No Data Available"

### ISSUE THREAD

**Issue by Meharbi88** [NileshPatel17/ng-multiselect-dropdown#71]
Is it possible to place a custom text instead of "No Data Available" when there is no data?

**Comment by NileshPatel17** [comment]
I would be adding a new property for the same. please wait for the next release, probably by this weekend.

**Comment by NileshPatel17** [comment]
Its fixed in version 0.2.1

**Comment by Meharbi88** [comment]
@NileshPatel17

**Comment by NileshPatel17** [comment]
```
yarn add ng-multiselect-dropdown
```
or
```
npm install ng-multiselect-dropdown --save
```
