### ISSUE TITLE
Reactive form Disable is not working

### ISSUE THREAD

**Issue by MohamedSahir** [NileshPatel17/ng-multiselect-dropdown#73]
I am using this control, when i try to disable the form which is not working
https://stackblitz.com/edit/angular-ftwwks?file=src%2Fapp%2Fapp.component.ts

**Comment by NileshPatel17** [comment]
You have to use 'disabled' property. below the code
```
template code:
<form [formGroup]="ngMultiSelect">
<ng-multiselect-dropdown
  [placeholder]="'custom placeholder'"
  [data]="dropdownList"
  formControlName ="Name"
  [settings]="dropdownSettings"
  (onSelect)="onItemSelect($event)"
  (onSelectAll)="onSelectAll($event)"
  formControlName ="Name"
  [disabled]="disabled"
>
</ng-multiselect-dropdown>
</form>


<button class="btn btn-danger" (click)="Reset()">Disable</button>
<pre>{{ngMultiSelect.value | json}}</pre>
```

```
Reset() {
    // this.ngMultiSelect.isDropdownOpen =false
    this.disabled = true
  }
```

you must declare the variable at the top
```
disabled: false
```

**Comment by MohamedSahir** [comment]
@NileshPatel17  i have disabled by using template driven approach ,why reactive disable() not working ,can you explanation for my understanding,not this control,so many third party control behaves like this..
