### ISSUE TITLE
Select all for filtered items in multiselect

### ISSUE THREAD

**Issue by MiRush94** [NileshPatel17/ng-multiselect-dropdown#75]
It would be nice, if the select all checkbox would only select the items I filtered for.
eg.: If I have 1000 list items, and search for something and now see 50 in the list and then click select all, it would be nice if only those 50 would get selected. Any chance this will be implemented in the future?

**Comment by NileshPatel17** [comment]
It will be done soon.

**Comment by EylonSu** [comment]
anything new?

**Comment by sanjeev02saraswat** [comment]
still this search filter to select all only searched item not working...when we can expect this fix..

**Comment by michael-perryman** [comment]
As of version 0.2.10, this change isn't reflected in the compiled ng-multiselect-dropdown/fesm5/ng-multiselect-dropdown.js file from NPM.  

How would I go about getting this code change?
