### ISSUE TITLE
(onFilterChange)="onFilterChange($event)" does not fire

### ISSUE THREAD

**Issue by MiRush94** [NileshPatel17/ng-multiselect-dropdown#76]
Hi, I use this multiselect with reactive-forms, but the event mentioned in title does not fire. Any chance to get this fixed?

<ng-multiselect-dropdown [placeholder]="'Select filters...'" [data]="filters" formControlName="reportingFilters" [settings]="filterDropdownSettings"
              (onSelectAll)="onSelectAllFilters($event)" **(onFilterChange)="onFilterChange($event)"**>
            </ng-multiselect-dropdown>

**Comment by hir06** [comment]
Hi @NileshPatel17 can you keep a code of above example as well?
it's hard to identify if function is getting triggered or not. moreover we'll have idea if we are passing any wrong params.

Thanks,
Hiral

**Comment by NileshPatel17** [comment]
@hir06 i have planned to create such sample codes and have links in readme. its just not getting time but surely will do it soon. Thanks!
