### ISSUE TITLE
When clicked on one checkbox - its populating 2 times

### ISSUE THREAD

**Issue by Rishabhjainbvp** [NileshPatel17/ng-multiselect-dropdown#9]
Hi

When I am trying to click on one checkbox , its populating 2 times.

Please help.

![image](https://user-images.githubusercontent.com/26934000/37354516-23c9ea30-26e2-11e8-9262-5ba117206874.png)

**Comment by NileshPatel17** [comment]
I am unable to reproduce the issue. Please share more details.
Appreciate if you can create sample project using online editor such as stackblitz.com or codesandbox.com and share the link.
Thanks!

**Comment by Rishabhjainbvp** [comment]
Hi

I cannot put the code but I can explain you the scenario.

Step1: I am creating a form and saving the value on server. (Screenshot below) - **Working perfect.**

![image](https://user-images.githubusercontent.com/26934000/37391866-e185cef6-276c-11e8-8240-2c72481d9555.png)


Step2: In order to modify the data, I am using inline editing. When I enable inline editing,
this is what I get.  **Working perfect.**
![image](https://user-images.githubusercontent.com/26934000/37391906-0180cfd0-276d-11e8-8067-ef8af7b44559.png)

Step3:  Now when I try to add a field .. it gets added 2 times
![image](https://user-images.githubusercontent.com/26934000/37391937-1c4727b0-276d-11e8-868a-d02d9538ae71.png)

Code for step3:

html:
-----
<angular2-multiselect [data]="itemList" [attr.value]="FieldsList" [(ngModel)]="FieldsList" [settings]="settings" (onSelect)="onItemSelect($event)" (onDeSelect)="OnItemDeSelect($event)" (onSelectAll)="onSelectAll($event)" (onDeSelectAll)="onDeSelectAll($event)"
                    name="FieldsList">
                </angular2-multiselect>
TS:
---


export class TestComponent implements OnInit {

 itemList = [];
  FieldsList: Array<any> = [];
  settings = {};
  
   ngOnInit() {

    this.itemList = [
      {'id': 1, 'itemName': 'Field 1'},
      {'id': 2, 'itemName': 'Field 2'},
      {'id': 3, 'itemName': 'Field 3'},
      {'id': 4, 'itemName': 'Field 4'},
      {'id': 5, 'itemName': 'Field 5'},
      {'id': 6, 'itemName': 'Field 6'},
      {'id': 7, 'itemName': 'Field 7'},
      {'id': 8, 'itemName': 'Field 8'},
      {'id': 9, 'itemName': 'Field 9'},
      {'id': 10, 'itemName': 'Field 10'}
    ];

  }
  
  onItemSelect(item: any) {
    this.replacePermission(item);
  }
  
  replacePermission(event) {
    console.log('event:: ', event);
    this.FieldsList.push(event);
    console.log('this.FieldsList:: ', this.FieldsList);
   // console.log('this.uniqueArraybyId:: ', this.uniqueArraybyId(this.FieldsList));
  //   this.uniqueArraybyId(this.FieldsList);
     console.log('this.FieldsList again:: ', this.FieldsList);
    this.thereAreChanges = true;
    this.cdr.detectChanges();
  }
  
  uniqueArraybyId(collection) {
      console.log('collection:: ', collection);
      const output = [],
          keys = [];
          console.log('collection.length:: ', collection.length);
          for (let item = 0; item < collection.length; item++) {
            const key = collection[item].id;
            console.log('key:: ', key);
            console.log('keys.indexOf(key):: ', keys.indexOf(key));
            if (keys.indexOf(key) === -1) {
                keys.push(key);
                output.push(collection[item]);
            }
          }
          console.log('output:: ', output);
          this.FieldsList = output;
return this.FieldsList;
}

 confirm() {
    this.loadingPending = true;
    console.log('this.FieldsList in confirm:: ', this.FieldsList);
    this.changedPermission.FieldsList = this.uniqueArraybyId(this.FieldsList);
// HTTP call
}
}

Please help.

**Comment by NileshPatel17** [comment]
My observations:-
1. By looking at the code, you are not following guidelines to use this component.
2. On item selection, what do you want to do?
I am giving you an example.
        _<ng-multiselect-dropdown name="city" [data]="cities" [(ngModel)]="selectedItems" [settings]="dropdownSettings" (onSelect)="onItemSelect($event)"
          [disabled]="disabled">
        </ng-multiselect-dropdown>_

Here whenever an item is selected, all selected items will be available in the variable - _selectedItems_
you do not need to add it( you are pushing it manually)
The reason why you are getting duplicate items:-
When you are selecting an item, its get added to _selectedItems_ and you are adding it manually as well.

**I do not have time to copy-paste your code. Please share it using stackblitz.com or codesandbox.com**

Hope this helps.
Nilesh Patel

**Comment by Rishabhjainbvp** [comment]
Hi

Thanks for the response.

It worked finally.

One more query:

How to check whether I have selected atleast one item before enabling the
submit button.

**Comment by NileshPatel17** [comment]
just like we do it with normal html control such as input ,select etc. Follow same pattern.
