### ISSUE TITLE
Is there a way to add a function on close of dropdown?

### ISSUE THREAD

**Issue by biswajit358** [NileshPatel17/ng-multiselect-dropdown#93]
I want to run a function on the close of function. 
closeDropdown : function(){
                console.log("dropdown close triggered");
                }

**Comment by wwywu** [comment]
looking for the same thing. any updates on how to get this to work? Thank you.

**Comment by NileshPatel17** [comment]
@biswajit358 	@wwywu 	
please wait for next release. Probable in next 2-3 days.
Thanks for your patience.

Happy Coding!!

**Comment by fmandres92** [comment]
Someone has been able to solve this error??

**Comment by NileshPatel17** [comment]
@fmandres92 Its done. available in latest release.

**Comment by jeevananthamDviVert** [comment]
onDropdownClose() this method is not working.
